name: Other Issue
description: Report an issue that does not fit the available reporting categories (bug, feature request, etc.).
title: "[Other] "
labels:
  - needs-triage
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your concern
      description: |
        Please explain your issue clearly.
        If this is a bug, include steps to reproduce.
      placeholder: Please be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, videos, etc.
